[project]
name = "bencherclient"
version = "0.1.0"
description = ""
authors = [{ name = "Leonard Papenmeier", email = "leonard.papenmeier@gmail.com" }]
requires-python = "~=3.11"
readme = "README.md"
dependencies = ["bencherscaffold>=0.3.1,<0.4"]

[project.scripts]
client-start = "bencherclient.client:main"

[dependency-groups]
dev = ["requests>=2.31.0,<3"]

[tool.hatch.build.targets.sdist]
include = ["./bencherclient"]

[tool.hatch.build.targets.wheel]
include = ["./bencherclient"]

[tool.hatch.build.targets.wheel.sources]
"./bencherclient" = "bencherclient"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
